### ISSUE TITLE
[DS] Focus Point API 리뷰

### ISSUE THREAD

**Issue by robert-min** [FLYAI4/focus-point-research#1]
### 📌 Description

미술 작품 Focus Point 구현을 위해 기존의 API를 리뷰합니다.

<br>

### 🎈 Goal
<p>$\tiny{구체적인\ 산출물을\ 포함한\ 목표를\ 작성해주세요.}$</p>

- API 리뷰
  - Focus Point를 구현하는 API 리서치
  - 해당 API를 활용하여 실제 기능 구현(Output 확인)
- 기술 공유
  - docs repo를 활용하여 팀원들에게 리서치 및 구현 내용 공유

<br>

### ✏️ Todo
<p>$\tiny{목표\ 달성을\ 위해\ 해야할\ 일을\ 세부적으로\ 작성해주세요.}$</p>

- [x] 강덕 자료 확인 📅 2024-01-18
- [ ] API 리뷰 📅 2024-01-24
  - [ ] API 구현 방법 리뷰
  - [ ] API 실제 기능 구현
- [ ] 기술 공유 📅 2024-01-26
