### ISSUE TITLE
[DS] focus point - api research task

### ISSUE THREAD

**Issue by kimdoeon** [FLYAI4/focus-point-research#10]
### 📌 Description
focus point api 구현을 위한 task 정의

<br>

### 🎈 Goal
<p>$\tiny{구체적인\ 산출물을\ 포함한\ 목표를\ 작성해주세요.}$</p>

### ✏️ Todo
<p>$\tiny{목표\ 달성을\ 위해\ 해야할\ 일을\ 세부적으로\ 작성해주세요.}$</p>

- [x]  **api 리서치(가격/사용가능 여부 등)**
    - [x]  llava
    - [x]  gpt4
    - [x]  cogNet
- [x]  **기능 테스트(** ~~llava~~ / ~~gpt4~~ / cogNet )
    - [x]  감상평 기반 키워드/좌표 추출
        - [x]  LVM을 이용한 감상평(키워드 포함) 추출
        - [x]  감상평 기반 키워드 추출(prompting using gpt4, llava, cogNet....)
        - [x]  LVM을 이용한 좌표 추출
    - [x]  이미지 기반 키워드/좌표 추출
        - [x]  LVM을 이용한 키워드 추출
        - [x]  LVM을 이용한 좌표 추출
    - [x]  focus point - 설명 매칭
        - [x]  focus point : 좌표를 이용한 image crop
        - [x]  설명 : focus point 좌표 기반 설명 추출
        - [x]  focus point - 좌표 매칭 확인
    - [ ]  한국어 번역
- [x]  **api 동작 테스트**
- [x]  **기능 통합 테스트**
    - [ ]  기능 완성도
    - [x]  시간
    - [x]  가격

**Comment by heehminh** [comment]
프론트에서 해당 부분만 확대하는 기능 넣을거면 좌표 추출 해야돼! 그 좌표를 기준으로 확대해야 할듯
