### ISSUE TITLE
[DS] gpt버전 focus point 튜닝 

### ISSUE THREAD

**Issue by kimdoeon** [FLYAI4/focus-point-research#12]
### 📌 Description
gpt api를 이용한 focus point 기능을 튜닝합니다.
<br>

### 🎈 Goal
<p>$\tiny{구체적인\ 산출물을\ 포함한\ 목표를\ 작성해주세요.}$</p>

- content 정제(작품 해설 외 문장, 기호 제거 등)
- api seed 설정 조사 및 적용
- 페르소나 설정 조사 및 적용(도슨트처럼)
- 좌표 정확도 높이는 프롬프팅

<br>

### ✏️ Todo
<p>$\tiny{목표\ 달성을\ 위해\ 해야할\ 일을\ 세부적으로\ 작성해주세요.}$</p>

- [x] gpt4 api 리서치
  - [x] seed값 고정
  - [x] 페르소나 설정 방법
- [x] 파라미터 설정 적용 
- [x] 프롬프팅 리서치 및 적용
- [x] content 정제
  - [x] 기호, 필요 없는 문장 등 제거
- [x] 한국어 번역
 
* 추가
- [ ] gpt 파인튜닝 리서치
